# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/krishnan/qt_projects/lineedits

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/krishnan/qt_projects/lineedits

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/krishnan/qt_projects/lineedits/CMakeFiles /home/krishnan/qt_projects/lineedits/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/krishnan/qt_projects/lineedits/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lineedits

# Build rule for target.
lineedits: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lineedits
.PHONY : lineedits

# fast build rule for target.
lineedits/fast:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/build
.PHONY : lineedits/fast

#=============================================================================
# Target rules for targets named lineedits_autogen

# Build rule for target.
lineedits_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lineedits_autogen
.PHONY : lineedits_autogen

# fast build rule for target.
lineedits_autogen/fast:
	$(MAKE) -f CMakeFiles/lineedits_autogen.dir/build.make CMakeFiles/lineedits_autogen.dir/build
.PHONY : lineedits_autogen/fast

lineedits_autogen/mocs_compilation.o: lineedits_autogen/mocs_compilation.cpp.o

.PHONY : lineedits_autogen/mocs_compilation.o

# target to build an object file
lineedits_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/lineedits_autogen/mocs_compilation.cpp.o
.PHONY : lineedits_autogen/mocs_compilation.cpp.o

lineedits_autogen/mocs_compilation.i: lineedits_autogen/mocs_compilation.cpp.i

.PHONY : lineedits_autogen/mocs_compilation.i

# target to preprocess a source file
lineedits_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/lineedits_autogen/mocs_compilation.cpp.i
.PHONY : lineedits_autogen/mocs_compilation.cpp.i

lineedits_autogen/mocs_compilation.s: lineedits_autogen/mocs_compilation.cpp.s

.PHONY : lineedits_autogen/mocs_compilation.s

# target to generate assembly for a file
lineedits_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/lineedits_autogen/mocs_compilation.cpp.s
.PHONY : lineedits_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/main.cpp.s
.PHONY : main.cpp.s

window.o: window.cpp.o

.PHONY : window.o

# target to build an object file
window.cpp.o:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/window.cpp.o
.PHONY : window.cpp.o

window.i: window.cpp.i

.PHONY : window.i

# target to preprocess a source file
window.cpp.i:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/window.cpp.i
.PHONY : window.cpp.i

window.s: window.cpp.s

.PHONY : window.s

# target to generate assembly for a file
window.cpp.s:
	$(MAKE) -f CMakeFiles/lineedits.dir/build.make CMakeFiles/lineedits.dir/window.cpp.s
.PHONY : window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lineedits"
	@echo "... lineedits_autogen"
	@echo "... lineedits_autogen/mocs_compilation.o"
	@echo "... lineedits_autogen/mocs_compilation.i"
	@echo "... lineedits_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

